### ISSUE TITLE
Updating Londrina on Google Fonts

### ISSUE THREAD

**Issue by m4rc1e** [marcelommp/Londrina-Typeface#1]
Hey,

I'd like to update this family on Google Fonts; in order to tackle this bug, https://github.com/google/fonts/issues/69

I'd like to change the font naming of the latest release so it conforms to our api and is easy for users.

I propose the following name changes:

```
LondrinaBlack-Regular.ttf --> LondrinaSolid-Black.ttf
LondrinaThin-Regular.ttf  --> LondrinaSolid-Thin.ttf
LondrinaBook-Regular.ttf  --> LondrinaSolid-Light.ttf (we can't have book weights in the api)
```

cc @davelab6

**Comment by davelab6** [comment]
I agree with these changes

**Comment by marcelommp** [comment]
Good! Finally the whole family will be available at google fonts.

**Comment by m4rc1e** [comment]
Thanks, I'll implement this today.
