### ISSUE TITLE
A character

### ISSUE THREAD

**Issue by ricardogonma** [marcelommp/Londrina-Typeface#10]
The character × that uses woocommerce is not available in the font. Could it be included?
It is different from the keyboard x (lowercase) and X (uppercase).

**Comment by marcelommp** [comment]
I'm assuming this is the multiplication sign U+00D7 that is included in the font file and I'm also assuming that I did a quite strange drawing for that symbol. Londrina has a lot of new characters that are not yet in the google fonts version, I'll consider that for the new release.

<img width="621" alt="Screen Shot 2020-01-13 at 12 36 20 PM" src="https://user-images.githubusercontent.com/12647948/72269100-c9661880-3601-11ea-9693-a0b28a8d90e5.png">

**Comment by ricardogonma** [comment]
Thank you for responding so soon and keep that in mind.
