### ISSUE TITLE
Before next release, update RFNs

### ISSUE THREAD

**Issue by davelab6** [marcelommp/Londrina-Typeface#3]
@m4rc1e Alas, https://github.com/marcelommp/Londrina-Typeface/commit/7f4129ee609e13f4dc9bcdce6f8a08f5d9bc8060 isn't quite right :) 

While I merged the recent Londrina updates (eg https://github.com/google/fonts/pull/1084/files) the RFN is changed in the GF repo to be for each one, but it should be reverted to only be "Londrina" in the next update. 

This isn't a big deal in itself, but before the next update, this could be fixed :) 

Indeed, ideally the RFN could be removed, per https://github.com/simoncozens/silson/issues/1

**Comment by davelab6** [comment]
Indeed, ideally the RFN could be removed, per https://github.com/simoncozens/silson/issues/1

**Comment by m4rc1e** [comment]
@davelab6 thanks, I'll make a note of this on the repo doc
