### ISSUE TITLE
Open vowels for lingála

### ISSUE THREAD

**Issue by eruedin** [marcelommp/Londrina-Typeface#5]
Lingála is a Bantu language with seven vowels. That means, there is also the open E (https://en.wikipedia.org/wiki/Latin_epsilon) and the open O (https://en.wikipedia.org/wiki/Open_O). In addition, the tone is marked, i.e. three different accents are added to all vowels (see https://ln.wikipedia.org/wiki/Utilisateur:Moyogo#Accents_et_caract%C3%A8res_sp%C3%A9ciaux ).
 
Considering that almost no fonts support the open vowels used in the Bantu languages, it would be extremely generous if you could add these two letters and the accents to your font.
ɔ   ɔ́  ɔ̂   ɔ̌   ɛ   ɛ́  ɛ̂   ɛ̌   a   á   â   ǎ    u   ú   û   ǔ    o   ó   ô   ǒ   i   í   î   ǐ

**Comment by marcelommp** [comment]
I had some problems with the unicode of accented glyphs but I hope this version works, take a look :)

https://github.com/marcelommp/Londrina-Typeface/tree/master/LastFontFiles
