### ISSUE TITLE
Alternative £ pound sign

### ISSUE THREAD

**Issue by bars1-07** [marcelommp/Londrina-Typeface#6]
![poundsign](https://user-images.githubusercontent.com/12826295/42567838-0b8ddd80-8503-11e8-8ce4-66e27b35fa4c.jpg)

Hey,
Absolutely in love with this font, the weighting, the playful edges are just so good.

My only pain point is the GBP pound sign... It's just a little close to the 'lowercase t'.
Do you think it would be possible to include an amended version with a small adjustment?
I have attached a preview idea to a possible fix, by just adding an extended terminal at the top, but not too overshoot the base terminal, just to be tucked in a little... I think it keeps that super friendly feel.

I really hope you get to this soon, I do want to use this font in all its forms!
Thanks so much

Scott

**Comment by marcelommp** [comment]
Great suggestion, consider done 😀

**Comment by bars1-07** [comment]
Amazing! Perfect! Thanks for your time and effort, really appreciate it.

**Comment by marcelommp** [comment]
Done! :)

https://github.com/marcelommp/Londrina-Typeface/tree/master/LastFontFiles

**Comment by bars1-07** [comment]
Perfect! Thanks so much!
