### ISSUE TITLE
Need some Central European character

### ISSUE THREAD

**Issue by tomtom125** [marcelommp/Londrina-Typeface#8]
Hi,

I need some Central European (Hungarian) characters (ő,Ő, Ű, ű) but those are not provided in these font.
I have put them into the .ttf file, if I send it to you will you release it? So I could use it for my webpage.

Thank you,
Tom

**Comment by marcelommp** [comment]
Hi Tom, I'll include this characters in the next release, but I can't say how long it takes to be published  in google fonts, so I think you have to use your own new .ttf file in your website.

**Comment by tomtom125** [comment]
Hi Marcel, 
Ok thanks. 
Tom

**Comment by marloes94** [comment]
Hi Marcel,

Is this problem already solved? I reported this problem on github, but they advised me to do it here. I have problems with the font for Polish. These are characters like: ł, ą, ż, ś, ń, ę, ć.
Probably later on, I may need characters for Hungarian and others as well.

Thank you in advance!
Marloes

**Comment by marcelommp** [comment]
Hi @marloes94 
I'm expanding Londrina set but it is still a working in progress. If is something urgent I can help you with the characters you need until we have the next release. What version of Londrina are you using? Do you need it for a specific weight?

**Comment by marloes94** [comment]
Hi Marcelo,

That's super nice to hear! Thank you for helping.
We use the font for e-trainings in different languages. We need the update
as fast as possible.
Preferably we want to use Londrina for all languages. But when it takes a
long time to expand the font, we are going to look for a alternative font
for a few languages.
When do you think that the updated font could be updated into Google Fonts?

Thank you in advance!

Marloes Dekkers

Op di 15 mrt. 2022 om 22:01 schreef Marcelo Magalhães <
***@***.***>:

**Comment by marloes94** [comment]
Hi Marcelo,

Do you have a status for me already. Than we could make descisions about
the font.
Thank you in advance!

Marloes Dekkers

Op vr 1 apr. 2022 om 11:58 schreef Marloes Dekkers <
***@***.***>:

**Comment by marcelommp** [comment]
Hi Marloes,
Still working in a massive revision, it happens that Londrina is my first font and it's a _mess_ that I'm finally fixing using a new software to make it more accessible and easy for updates. I'll be publishing here a multilingual version in the next few months.

**Comment by marcelommp** [comment]
The updated OTF and TTF files are available now for download :)
